// functions/01af8 — 1 functions
#include "libGameKindred.h"




void FUN_01af8a08(undefined8 param_1,EC_POINT *param_2,EC_KEY *param_3,undefined1 *param_4)

{
  BIGNUM *a;
  EC_GROUP *pEVar1;
  EC_POINT *r;
  BN_CTX *ctx;
  BIGNUM *b;
  BIGNUM *r_00;
  BIGNUM *order;
  BIGNUM *x;
  BIGNUM *y;
  undefined1 auStack_168 [120];
  undefined1 local_f0;
  undefined1 local_ef;
  undefined1 local_ee;
  undefined1 local_ed;
  undefined1 local_ec;
  undefined1 local_eb;
  undefined1 local_ea;
  undefined1 local_e9;
  undefined1 local_e8;
  undefined1 local_e7;
  undefined1 local_e6;
  undefined1 local_e5;
  undefined1 local_e4;
  undefined1 local_e3;
  undefined1 local_e2;
  undefined1 local_e1;
  undefined1 local_e0;
  undefined1 local_df;
  undefined1 local_de;
  undefined1 local_dd;
  undefined1 local_dc;
  undefined1 local_db;
  undefined1 local_da;
  undefined1 local_d9;
  undefined1 local_d8;
  undefined1 local_d7;
  undefined1 local_d6;
  undefined1 local_d5;
  undefined1 local_d4;
  undefined1 local_d3;
  undefined1 local_d2;
  undefined1 local_d1;
  undefined1 local_d0;
  undefined1 local_cf;
  undefined1 local_ce;
  undefined1 local_cd;
  undefined1 local_cc;
  undefined1 local_cb;
  undefined1 local_ca;
  undefined1 local_c9;
  undefined1 local_c8;
  undefined1 local_c7;
  undefined1 local_c6;
  undefined1 local_c5;
  undefined1 local_c4;
  undefined1 local_c3;
  undefined1 local_c2;
  undefined1 local_c1;
  undefined1 local_c0;
  undefined1 local_bf;
  undefined1 local_be;
  undefined1 local_bd;
  undefined1 local_bc;
  undefined1 local_bb;
  undefined1 local_ba;
  undefined1 local_b9;
  undefined1 local_b8;
  undefined1 local_b7;
  undefined1 local_b6;
  undefined1 local_b5;
  undefined1 local_b4;
  undefined1 local_b3;
  undefined1 local_b2;
  undefined1 local_b1;
  undefined1 local_b0;
  undefined1 local_af;
  undefined1 local_ae;
  undefined1 local_ad;
  undefined1 local_ac;
  undefined1 local_ab;
  undefined1 local_aa;
  undefined1 local_a9;
  undefined1 local_a8;
  undefined1 local_a7;
  undefined1 local_a6;
  undefined1 local_a5;
  undefined1 local_a4;
  undefined1 local_a3;
  undefined1 local_a2;
  undefined1 local_a1;
  undefined1 local_a0;
  undefined1 local_9f;
  undefined1 local_9e;
  undefined1 local_9d;
  undefined1 local_9c;
  undefined1 local_9b;
  undefined1 local_9a;
  undefined1 local_99;
  undefined1 local_98;
  undefined1 local_97;
  undefined1 local_96;
  undefined1 local_95;
  undefined1 local_94;
  undefined1 local_93;
  undefined1 local_92;
  undefined1 local_91;
  undefined1 local_90;
  undefined1 local_8f;
  undefined1 local_8e;
  undefined1 local_8d;
  undefined1 local_8c;
  undefined1 local_8b;
  undefined1 local_8a;
  undefined1 local_89;
  undefined1 local_88;
  undefined1 local_87;
  undefined1 local_86;
  undefined1 local_85;
  undefined1 local_84;
  undefined1 local_83;
  undefined1 local_82;
  undefined1 local_81;
  undefined1 local_80;
  undefined1 local_7f;
  undefined1 local_7e;
  undefined1 local_7d;
  undefined1 local_7c;
  undefined1 local_7b;
  undefined1 local_7a;
  undefined1 local_79;
  undefined1 local_78;
  undefined1 local_77;
  undefined1 local_76;
  undefined1 local_75;
  undefined1 local_74;
  undefined1 local_73;
  undefined1 local_72;
  undefined1 local_71;
  undefined1 local_70;
  undefined1 local_6f;
  undefined1 local_6e;
  undefined1 local_6d;
  undefined1 local_6c;
  undefined1 local_6b;
  undefined1 local_6a;
  undefined1 local_69;
  
  a = EC_KEY_get0_private_key(param_3);
  pEVar1 = EC_KEY_get0_group(param_3);
  r = EC_POINT_new(pEVar1);
  ctx = BN_CTX_new();
  local_69 = *param_4;
  local_6a = param_4[1];
  local_6b = param_4[2];
  local_6c = param_4[3];
  local_6d = param_4[4];
  local_6e = param_4[5];
  local_6f = param_4[6];
  local_70 = param_4[7];
  BN_CTX_start(ctx);
  b = (BIGNUM *)getbnfrombuf(&local_70,8);
  r_00 = BN_CTX_get(ctx);
  order = BN_CTX_get(ctx);
  x = BN_CTX_get(ctx);
  y = BN_CTX_get(ctx);
  pEVar1 = EC_KEY_get0_group(param_3);
  EC_GROUP_get_order(pEVar1,order,ctx);
  BN_mod_mul(r_00,a,b,order,ctx);
  pEVar1 = EC_KEY_get0_group(param_3);
  EC_POINT_mul(pEVar1,r,(BIGNUM *)0x0,param_2,r_00,ctx);
  pEVar1 = EC_KEY_get0_group(param_3);
  EC_POINT_get_affine_coordinates_GFp(pEVar1,r,x,y,ctx);
  store_bignum(y,&local_b0,0x20);
  store_bignum(x,&local_90,0x20);
  local_b1 = local_b0;
  local_b2 = local_af;
  local_b3 = local_ae;
  local_b4 = local_ad;
  local_b5 = local_ac;
  local_b6 = local_ab;
  local_b7 = local_aa;
  local_b8 = local_a9;
  local_b9 = local_a8;
  local_ba = local_a7;
  local_bb = local_a6;
  local_bc = local_a5;
  local_bd = local_a4;
  local_be = local_a3;
  local_bf = local_a2;
  local_c0 = local_a1;
  local_c1 = local_a0;
  local_c2 = local_9f;
  local_c3 = local_9e;
  local_c4 = local_9d;
  local_c5 = local_9c;
  local_c6 = local_9b;
  local_c7 = local_9a;
  local_c8 = local_99;
  local_c9 = local_98;
  local_ca = local_97;
  local_cb = local_96;
  local_cc = local_95;
  local_cd = local_94;
  local_ce = local_93;
  local_cf = local_92;
  local_d0 = local_91;
  local_d1 = local_90;
  local_d2 = local_8f;
  local_d3 = local_8e;
  local_d4 = local_8d;
  local_d5 = local_8c;
  local_d6 = local_8b;
  local_d7 = local_8a;
  local_d8 = local_89;
  local_d9 = local_88;
  local_da = local_87;
  local_db = local_86;
  local_dc = local_85;
  local_dd = local_84;
  local_de = local_83;
  local_df = local_82;
  local_e0 = local_81;
  local_e1 = local_80;
  local_e2 = local_7f;
  local_e3 = local_7e;
  local_e4 = local_7d;
  local_e5 = local_7c;
  local_e6 = local_7b;
  local_e7 = local_7a;
  local_e8 = local_79;
  local_e9 = local_78;
  local_ea = local_77;
  local_eb = local_76;
  local_ec = local_75;
  local_ed = local_74;
  local_ee = local_73;
  local_ef = local_72;
  local_f0 = local_71;
  init_gost_hash_ctx(auStack_168,GostR3411_94_CryptoProParamSet);
  start_hash(auStack_168);
  hash_block(auStack_168,&local_f0,0x40);
  finish_hash(auStack_168,param_1);
  done_gost_hash_ctx(auStack_168);
  BN_free(b);
  BN_CTX_end(ctx);
  BN_CTX_free(ctx);
  EC_POINT_free(r);
  return;
}

